### ISSUE TITLE
hunter come back to society

### ISSUE THREAD

**Issue by Dadik11** [Hunter-171/Liquidbounce-Scripts#1]

**Comment by Hunter-171** [comment]
update soon

**Comment by Dadik11** [comment]
> update soon

what was ur ign me and body got termed for ectasy xd

**Comment by Dadik11** [comment]
I mean discord

**Comment by Dadik11** [comment]
![Screenshot 2022-11-09 193730](https://user-images.githubusercontent.com/98746815/200913395-649a03ce-7d58-4da7-a2a0-0d3ba5cc2978.png)

**Comment by Hunter-171** [comment]
> > update soon
> 
> what was ur ign me and body got termed for ectasy xd

im still in the superhero server

**Comment by Dadik11** [comment]
men i don work for ely

**Comment by Dadik11** [comment]
@Hunter-171
